name: Swift

on:
  push:
    branches: [ "main", "feature/**", "test/action" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    name: Xcode build Test And Vegeting Test
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Default Scheme
        run: xcodebuild clean test -project Vegeting.xcodeproj -scheme "Vegeting" -destination "platform=iOS Simulator,name=iPhone 13 Pro,OS=15.0" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
